Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = "yungsang/boot2docker"
  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.provider "virtualbox" do |v|
    v.name = "boot2docker"
    v.check_guest_additions = false
    v.functional_vboxsf = false
    v.memory = 2048
    v.cpus = 4
  end
end
