---
- hosts: loadbalancers
  tasks: []

- hosts: webservers
  serial: 1
  tasks:
    - name: disable the server in lb
      shell: echo "disable server goto_app/{{ ansible_hostname }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: groups.loadbalancers

    - name: sleep 2 sec
      command: /bin/sleep 2

    - name: replace index.html
      template: src=files/index.html.j2 dest=/var/www/html/index.html

   - name: copy image
      copy: src=files/pizza.gif dest=/var/www/html/

    - name: enable the server in lb
      shell: echo "enable server goto_app/{{ ansible_hostname }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: groups.loadbalancers
