Vagrant.require_version ">= 1.6.0"

VAGRANT_API_VERSION = '2'

Vagrant.configure(VAGRANT_API_VERSION) do |config|

  config.ssh.username = "root"
  config.ssh.private_key_path = "zilverline.key"
  config.ssh.port = 22
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :docker do |d|
    d.image = "zilverline/baseimage"
    d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
    d.has_ssh = true
    d.vagrant_vagrantfile = "./docker/Vagrantfile"
  end

  (1..6).each do |i|
    config.vm.define "webserver#{i}" do |c|
      c.vm.network :forwarded_port, guest: 22, host: 2200 + i, auto_correct: false, id: "ssh"
    end
  end

  config.vm.define "loadbalancer" do |l|
    l.vm.network :forwarded_port, guest: 22, host: 2200, auto_correct: false, id: "ssh"
    l.vm.network :forwarded_port, guest: 80, host: 8800, auto_correct: false
  end

end
