Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "goto" do |w|
    w.vm.network :private_network, ip: "192.168.10.11"
  end

end
