---
- name: install haproxy
  apt: pkg={{ item }} state=present update_cache=true cache_valid_time=3600
  with_items:
    - haproxy
    - socat
  tags: haproxy

- name: enable haproxy to start
  copy: src=haproxy dest=/etc/default/haproxy owner=root group=root mode=0644
  notify: restart haproxy
  tags: haproxy

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    owner=root group=root mode=0644
  notify: restart haproxy
  tags: haproxy
